import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: "al" | "en" };
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout locale={params.locale}>{children}</Layout>
      </body>
    </html>
  );
}
